### ISSUE TITLE
MathJax in description: Swapping between rendered eqn and latex code

### ISSUE THREAD

**Issue by softmonaut** [otacke/h5p-agamotto#405] opened 2023-03-31 07:46 UTC
Hi,
I've made a strange observation: when using Mathjax latex code in the image description, the display continuously swaps between the rendered eqn and the MathJax latex code. Same when using \(...\) inline delimiters.
Can anyone confirm the behavior?
Thx Jörg

Agamotto (1.5.2):
![h5p-agamotto-mathjax](https://user-images.githubusercontent.com/6533743/229056521-5d76ab87-592c-4647-86bc-c2a8066d54d4.gif)

**Comment by otacke** [comment] 2023-03-31 07:52
@softmonaut If you post this as an issue for the repository maintainers, "anyone" is "them", and in this particular case only me.

I will gladly look what the cause might be, but it's the MathDisplay library that is rendering LaTeX via MathJax, not the content type. It's possible that some side effect is causing the re-rendering.

**Comment by otacke** [comment] 2023-03-31 08:35
I can reproduce this behavior on h5p.org which is using Agamotto 1.5.2 (which has been outdated for close to 2 years now), but not with the latest release version of Agamotto which is 1.6.4.

You can download and install that version via uploading the demo content on https://www.olivertacke.de/labs/2017/04/14/agamotto-as-if-it-way-yesterday/ but that will not help if you're using Agamotto as subcontent in some other content type that still references the old version, e.g. Column. The H5P core team should update their libraries to handle that.

**Comment by otacke** [comment] 2023-08-01 10:02
Closing this as no further comment was received, so I assume that version 1.6 is fine.

**Closed by otacke** 2023-08-01 10:02 UTC
